"""create video task batches

Revision ID: 0008
Revises: 0007_tiktok_studio_trace
Create Date: 2026-10-05 17:39:43.784840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007_tiktok_studio_trace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pipeline_key', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['platform.user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'request_id', name='uq_batch_created_request'),
    schema='mod_tiktok_studio'
    )
    op.create_index('ix_batch_created_by', 'batch', ['created_by', 'created_at'], unique=False, schema='mod_tiktok_studio')
    op.create_index('ix_batch_status', 'batch', ['status'], unique=False, schema='mod_tiktok_studio')
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_key', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('biz_key', sa.String(length=255), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['mod_tiktok_studio.batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['platform.user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'biz_key', name='uq_task_batch_bizkey'),
    schema='mod_tiktok_studio'
    )
    op.create_index('ix_task_admit', 'task', ['status', 'priority', 'created_at'], unique=False, schema='mod_tiktok_studio', postgresql_where=sa.text("status = 'admitted_pending'"))
    op.create_index('ix_task_batch', 'task', ['batch_id'], unique=False, schema='mod_tiktok_studio')
    op.create_index('ix_task_biz_key', 'task', ['biz_key'], unique=False, schema='mod_tiktok_studio')
    op.create_index('ix_task_created_by_status', 'task', ['created_by', 'status'], unique=False, schema='mod_tiktok_studio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_created_by_status', table_name='task', schema='mod_tiktok_studio')
    op.drop_index('ix_task_biz_key', table_name='task', schema='mod_tiktok_studio')
    op.drop_index('ix_task_batch', table_name='task', schema='mod_tiktok_studio')
    op.drop_index('ix_task_admit', table_name='task', schema='mod_tiktok_studio', postgresql_where=sa.text("status = 'admitted_pending'"))
    op.drop_table('task', schema='mod_tiktok_studio')
    op.drop_index('ix_batch_status', table_name='batch', schema='mod_tiktok_studio')
    op.drop_index('ix_batch_created_by', table_name='batch', schema='mod_tiktok_studio')
    op.drop_table('batch', schema='mod_tiktok_studio')
    # ### end Alembic commands ###
